Tidak mengerjakan diluar

##Aljabar Matrik
##Tidak mengerjakan tidak boleh masuk

- Berikan penjelasan tentang apa itu matrik
- Oprasi Matrik (penjumlahan, perkalian, pengurangan, transpose matrik)
- Buat Program untuk mengalikan matrik A dan B


Saya disuruh membuat matrik A dan B ukuran 3x3 dan C ukuran 3x2

A dan B MxN
C dan D NxK

N adalah Kolom dari A
N adalah Baris dari B

In [21]:
import numpy as np
import sympy as sy

A = np.array([[1,6,5],[2,8,3],[3,9,8]])
B = np.array([[1,6,2],[2,8,7],[3,9,3]])
C = np.array([[1,6],[2,8],[-2,6]])
D = np.array([[3,5,1],[-2,-3,5],[2,8,3]])
E = A+B
F = 2*A
G = A@C
H = B@C
# A(BC) = (AB)C
I = A@H
J = A@B
K = J@C
# Transpose
Ctrans = C.transpose()
Cova = Ctrans@C
Covab = C@Ctrans
Cova.shape
print(A)
print('\n')
print(B)
print('\n')
print(C)
print('\n')
print(D)
print('\n')
print(E)
print('\n')
print(F)
print('\n')
print(G)
print('coba')

print(I)
print(K)

print('\n')
print(Ctrans)
print(Cova)
print(Covab)




[[1 6 5]
 [2 8 3]
 [3 9 8]]


[[1 6 2]
 [2 8 7]
 [3 9 3]]


[[ 1  6]
 [ 2  8]
 [-2  6]]


[[ 3  5  1]
 [-2 -3  5]
 [ 2  8  3]]


[[ 2 12  7]
 [ 4 16 10]
 [ 6 18 11]]


[[ 2 12 10]
 [ 4 16  6]
 [ 6 18 16]]


[[  3  84]
 [ 12  94]
 [  5 138]]
coba
[[ 108 1314]
 [  95 1400]
 [ 183 2124]]
[[ 108 1314]
 [  95 1400]
 [ 183 2124]]


[[ 1  2 -2]
 [ 6  8  6]]
[[  9  10]
 [ 10 136]]
[[37 50 34]
 [50 68 44]
 [34 44 40]]
