# Aljabar Matrik
Tidak mengerjakan tidak boleh masuk

- Berikan penjelasan tentang apa itu matrik
- Oprasi Matrik (penjumlahan, perkalian, pengurangan, transpose matrik)
- Buat Program untuk mengalikan matrik A dan B



## Definisi Matrik

### 1. Penjelasan tentang matrik :
Matriks adalah sekumpulan bilangan yang disusun berdasarkan baris dan kolom, serta ditempatkan di dalam tanda kurung.\
Contoh: 
\begin{split}
A = \left[ \begin{array}{rrrr} 3 & 1 & 0 \\ 5 & 2 & 1 \\ 0 & 2 & 3\end{array}\right]\hspace{2cm}
C = \left[ \begin{array}{rrrr} 1 & 2  \\ 3 & 4  \\ 1 & 0  \end{array}\right]\hspace{2cm}
\end{split}


### 2. Jenis-Jenis Matrik :
Jenis-jenis matrik yaitu Matrik nol, matrik diagonal, matrik skalar, matrik simetris, matrik identitas, matrik segitiga atas, matrik segitiga bawah, matrik transpose.\

a. Matrik Nol adalah matrik yang semua elemennya penyusunnya nol:

\begin{split}
A = \left[ \begin{array}{rrrr} 0 & 0 & 0 \\ 0 & 0 & 0 \\ 0 & 0 & 0\end{array}\right]\hspace{2cm}
\end{split}

b. Matrik Diagonal adalah suatu matrik yang dimana elemen-elemen diagonalnya mempunyai nilai tidal sama dengan nol dan elemen-elemen selain diagonal bernilai nol:

\begin{split}
A = \left[ \begin{array}{rrrr} 1 & 0 & 0 \\ 0 & 2 & 0 \\ 0 & 0 & 3\end{array}\right]\hspace{2cm}
\end{split}

c. Matrik Skalar adalah matrik yang dimana elemen-elemen diagonalnya bernilai sama dan elemen-elemen selain diagonal bernilai nol:

\begin{split}
A = \left[ \begin{array}{rrrr} 3 & 0 & 0 \\ 0 & 3 & 0 \\ 0 & 0 & 3\end{array}\right]\hspace{2cm}
\end{split}

d. Matriks simetris adalah suatu matrik yang jika elemen-elemen matriks A yang terletak pada baris dan kolom yang sama memiliki nilai yang sama dengan elemen-elemen matriks A yang terletak pada baris dan kolom yang berlawanan: 

\begin{split}
A = \left[ \begin{array}{rrrr} 3 & 1 & 2 \\ 1 & 4 & 0 \\ 2 & 0 & 3\end{array}\right]\hspace{2cm}
\end{split}

e. Matrik Identitas adalah suatu matrik yang elemen-elemen diagonalnya mempunyai nilai 1, sedangkan selain elemen pada diagonal bernilai nol:

\begin{split}
A = \left[ \begin{array}{rrrr} 1 & 0 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 1\end{array}\right]\hspace{2cm}
\end{split}

f. Matrik Segitiga Atas adalah suatu matrik yang elemen-elemennya dibawah diagonal adalah nol:

\begin{split}
A = \left[ \begin{array}{rrrr} -2 & 6 & 1 \\ 0 & 2 & 3 \\ 0 & 0 & -2\end{array}\right]\hspace{2cm}
\end{split}

g. Matrik Segitiga Bawah adalah suatu matrik yang elemen-elemennya diatas diagonal adalah nol:

\begin{split}
A = \left[ \begin{array}{rrrr} -2 & 0 & 0 \\ 3 & -2 & 0 \\ 1 & 6 & -2\end{array}\right]\hspace{2cm}
\end{split}

h. Matrik Transpose merupakan matrik yang diperoleh dari memindahkan elemen-elemen baris menjadi kolom atau sebaliknya:\
Selelum Transpose:
\begin{split}
A = \left[ \begin{array}{rrrr} 1 & 2 & 3 \\ 4 & 5 & 6 \end{array}\right]\hspace{2cm}
\end{split}

Transpose:
\begin{split}
A^T = \left[ \begin{array}{rrrr} 1 & 4  \\ 2 & 5  \\ 3 & 6\end{array}\right]\hspace{2cm}
\end{split}


### 3. Penjelasan NumPy
NumPy (Numerical Python) adalah library dalam bahasa pemrograman Python yang digunakan untuk memanipulasi dan meanalisis data numerik. Numpy menyediakan fungsi yang siap pakai untuk memudahkan melakukan perhitungan saintifik seperti matriks, aljabar,dan statistik.

In [2]:
import numpy as np

### 4.  Operasi Matrik
A. Penjumlaan\
Suatu matrik A dan matrik B dapat dijumlahkan apabila matrik A dan Matrik B mempunyai ordo yang sama. Hasil penjumlahannya berupa matrik C dengan ordo yang sama dengan matrik A dan B.
1. Sifat komutatif
Pada sifat ini berlaku A + B = B + A.
2. Sifat asosiatif
Pada sifat ini berlaku (A + B) + C = A +(B + C)
3. Matriks nol
Pada sifat ini berlaku A + 0 = A
4. Jika dijumlahkan dengan lawannya akan menghasilkan matriks nol, yaitu A + (-A) = 0.

In [5]:
a = np.array(([5,8,2],[4,1,-4]))
b = np.array(([9,-4,2],[-2,-4,5]))

print('Ini Matrik a: ')
print(a)
print()
print('Ini Matrik b: ')
print(b)
print()
print('Hasil a + b: ')
print(a+b)

Ini Matrik a: 
[[ 5  8  2]
 [ 4  1 -4]]

Ini Matrik b: 
[[ 9 -4  2]
 [-2 -4  5]]

Hasil a + b: 
[[14  4  4]
 [ 2 -3  1]]


B. Pengurangan\
Suatu matrik A dan matrik B dapat dikurangkan apabila matrik A dan Matrik B mempunyai ordo yang sama. Hasil pengurangannya berupa matrik C dengan ordo yang sama dengan matrik A dan B.

In [6]:
a = np.array(([6,9,3],[-6,4,10]))
b = np.array(([2,9,3],[4,-6,-3]))

print('Ini Matrik a: ')
print(a)
print()
print('Ini Matrik b: ')
print(b)
print()
print('Hasil a - b: ')
print(a-b)

Ini Matrik a: 
[[ 6  9  3]
 [-6  4 10]]

Ini Matrik b: 
[[ 2  9  3]
 [ 4 -6 -3]]

Hasil a - b: 
[[  4   0   0]
 [-10  10  13]]


In [ ]:
#Perkalian pada matriks
#Matriks bisa di kalikan jika kedua matriks memiliki jumlah baris dan kolom yang sama

a = np.array(([1,2,3],[4,5,6],[4,5,6]))
b = np.array(([3,2,1],[-1,-2,-3],[7,5,6]))

hasil = np.dot(a,b)
print('Hasil a x b: ')
print(hasil)

Hasil a x b: 
[[22 13 13]
 [49 28 25]
 [49 28 25]]


In [ ]:
# Transpos suatu matriks diperoleh dengan memindahkan data baris ke kolom dan data kolom ke baris. Jika kita mempunyai array berbentuk (X, Y) maka transpos array tersebut akan berbentuk (Y, X).
a = np.array([[1, 2, 3], [4, 5, 6]])

arr1_transpose = a.transpose()

print('Sebulum di transpose: ')
print(a)

print('Sesudah di transpose: ')
print(arr1_transpose)

Sebulum di transpose: 
[[1 2 3]
 [4 5 6]]
Sesudah di transpose: 
[[1 4]
 [2 5]
 [3 6]]


In [ ]:
# Perkalian dua matrik tanpa numpy
math1 = [
    [5,0,4],
    [2,6,2],
    [1,4,1],]

math2 = [
    [1,0,3],
    [4,2,1],
    [2,3,1],]


hasil = [[0,0,0],[0,0,0],[0,0,0]]
for x in range(len(math1)):
    for y in range(len(math2[0])):
        for k in range(len(math1[0])):
            hasil[x][y]+= math1[x][k]*math2[k][y]
print('Hasil dari perkalian math 1 dan math 2: ')
for k in hasil:
    print(k)

Hasil dari perkalian math 1 dan math 2: 
[13, 12, 19]
[30, 18, 14]
[19, 11, 8]


In [ ]:
import numpy as np
import sympy as sy

A = np.array([[1,6,5],[2,8,3],[3,9,8]])
B = np.array([[1,6,2],[2,8,7],[3,9,3]])
C = np.array([[1,6],[2,8],[-2,6]])
D = np.array([[3,5,1],[-2,-3,5],[2,8,3]])
E = A+B
F = 2*A
G = A@C
H = B@C
# A(BC) = (AB)C
I = A@H
J = A@B
K = J@C
# Transpose
Ctrans = C.transpose()
Cova = Ctrans@C
Covab = C@Ctrans
Cova.shape
print(A)
print('\n')
print(B)
print('\n')
print(C)
print('\n')
print(D)
print('\n')
print(E)
print('\n')
print(F)
print('\n')
print(G)
print('coba')

print(I)
print(K)

print('\n')
print(Ctrans)
print(Cova)
print(Covab)




[[1 6 5]
 [2 8 3]
 [3 9 8]]


[[1 6 2]
 [2 8 7]
 [3 9 3]]


[[ 1  6]
 [ 2  8]
 [-2  6]]


[[ 3  5  1]
 [-2 -3  5]
 [ 2  8  3]]


[[ 2 12  7]
 [ 4 16 10]
 [ 6 18 11]]


[[ 2 12 10]
 [ 4 16  6]
 [ 6 18 16]]


[[  3  84]
 [ 12  94]
 [  5 138]]
coba
[[ 108 1314]
 [  95 1400]
 [ 183 2124]]
[[ 108 1314]
 [  95 1400]
 [ 183 2124]]


[[ 1  2 -2]
 [ 6  8  6]]
[[  9  10]
 [ 10 136]]
[[37 50 34]
 [50 68 44]
 [34 44 40]]
